Учебный проект: хрустящий CRUD
htmlacademy-nodejs/521287-buy-and-sell-3 pull request #11
Opened 2020-06-28 23:25 UTC by ilyasidorchik

2020-06-29 08:10 UTC, dean992008 requested changes

2020-06-29 08:10 UTC, dean992008 commented on src/service/lib/get-mock-data.js
> +    return Promise.resolve(data);
Думаю здесь `Promise.resolve` здесь линий, из `async` можно просто возвращать значение.

2020-06-29 08:10 UTC, dean992008 commented on src/service/middlewares/offerExists.js
> +  return next();
Мне кажется `return` здесь лишний.

2020-06-29 14:45 UTC, ilyasidorchik commented on src/service/lib/get-mock-data.js
> +    return Promise.resolve(data);
Потому что из-за асинхронной функции и так возвращается промис с `data`?

2020-06-29 15:06 UTC, ilyasidorchik commented on src/service/middlewares/offerExists.js
> +  return next();
Без него ошибка: `Expected to return a value at the end of arrow function`

2020-06-29 15:16 UTC, ilyasidorchik commented
У объекта `offer` поле называется `category` или `categories`? Это строка или массив строк?

2020-06-30 13:04 UTC, dean992008 commented on src/service/lib/get-mock-data.js
> +    return Promise.resolve(data);
Да, просто зачем еще 1? Он на уровне системы это выполнит, получаеться лишний код.

2020-06-30 13:08 UTC, dean992008 commented on src/service/middlewares/offerExists.js
> +  return next();
Ок.

2020-06-30 13:09 UTC, merged