Учебный проект: долгая прогулка
htmlacademy-nodejs/521287-buy-and-sell-3 pull request #19
Opened 2021-01-30 21:16 UTC by ilyasidorchik

2021-02-01 11:18 UTC, Krabaton requested changes
Так слишком много важных изменений за один раз. Обработка ошибок совсем не ясна. Некоторые вещи не очевидны. Илья надо созвонится.

2021-02-01 11:18 UTC, Krabaton commented on src/express/routes/main-routes.js
> +  const [_offers, categories] = await Promise.all([
У нас это не класс, почему подчеркивание? Это же не приватный метод

2021-02-01 11:18 UTC, Krabaton commented on src/express/routes/my-routes.js
>    res.render(`${ROOT}/comments`, {_offers: _offers.slice(0, 3)});
Нужен поясняющий комментарий, почему мы так делаем. Отрезаем только первые три части массива.

2021-02-01 11:18 UTC, Krabaton commented on src/express/routes/offers-routes.js
> +  const categories = await api.getCategories();
Вопрос, что будет если сервис вернет ошибку?
Каждый await это потенциальная ошибка и обработки ее или нет или она не очевидна.

2021-02-01 11:18 UTC, Krabaton commented on src/express/routes/offers-routes.js
> +  const _offer = await api.getOffer(id, true);
Опять все вместе подчеркивание и await

2021-02-01 11:18 UTC, Krabaton commented on src/express/routes/offers-routes.js
> +  res.render(`${ROOT}/category`));
Мы в шаблон ничего не передаем? Вроде же конкретную категорию просим :id

2021-02-01 11:18 UTC, Krabaton commented on src/service/api/categories/categories.e2e.test.js
> +const mockDB = new Sequelize(`sqlite::memory:`, {logging: false});
Это плохо, что для тестов мы юзаем не типовую базу. Могут возникать специфические ошибки.

2021-02-01 11:18 UTC, Krabaton commented on src/service/api/categories/mockData.js
> +const offer1Categories = mockCategories.slice(0, 2);
Так, что за названия такие? 1,2,3? Не информативно, надо догадываться для чего это было сделано. Переименовать или поясняющий комментарий.

2021-02-01 11:18 UTC, Krabaton commented on src/service/api/offers/mockData.js
> +const offer1Title = `Куплю антиквариат`;
Опять число. это же мок? offerFirstMockTitle, что-то типа такого. прочитал переменную и понял для чего она.

2021-02-01 11:18 UTC, Krabaton commented on src/service/api/offers/offers.js
> +    const {comments} = req.query;
вопрос. Где обработка если comments нет?, что будет если сервис выдал ошибку?

2021-02-01 11:18 UTC, Krabaton commented on src/service/api/offers/offers.js
> +    const offer = await service.create(req.body);
А если не создал?

2021-02-01 11:18 UTC, Krabaton commented on src/service/data-service/comments.js
> +    return wasDropped;
Зачем это? Почему бы просто не передать 
```js
 return Boolean(deletedRows);
```

2021-02-01 11:18 UTC, Krabaton commented on src/service/data-service/offers.js
> +    this._Offer = sequelize.models.Offer;
какая же сильная связность.

2021-02-01 12:22 UTC, ilyasidorchik commented on src/express/routes/main-routes.js
> +  const [_offers, categories] = await Promise.all([
Потому что шаблонизатор «Паг 3» выдаёт ошибку, если переменная начинается с ключевого слова: в моём случае с `of`.

[Баг в Паге 3](https://github.com/pugjs/pug/issues/3263)

2021-02-01 12:32 UTC, Krabaton commented on src/express/routes/main-routes.js
> +  const [_offers, categories] = await Promise.all([
так тогда передавай {_offers: offers} в сам шаблон. а лучше (pugOffers: offers) чтобы понять было, что не просто так это сделали.

2021-02-06 11:19 UTC, ilyasidorchik commented on src/express/routes/offers-routes.js
> +  const categories = await api.getCategories();
Связался с автором курса — будем обрабатывать ошибки и делать валидацию в следующем модуле.

2021-02-06 12:20 UTC, merged