Make cli generator
htmlacademy-nodejs/521287-buy-and-sell-3 pull request #2
Opened 2020-04-02 21:45 UTC by ilyasidorchik

2020-04-03 10:19 UTC, dean992008 requested changes

2020-04-03 10:19 UTC, dean992008 commented on src/constants.js
> +  success: 0,
В перечеслении ключи должны быть большыми буквами: https://up.htmlacademy.ru/ecmascript/11/criteries#b7

2020-04-03 10:19 UTC, dean992008 commented on src/data.js
> +const OfferType = {
Также ключи должны быть с большой буквы.

2020-04-03 10:19 UTC, dean992008 commented on src/service/cli/version.js
> +    const version = packageJsonFile.version;
Думаю здесь можно сразу выводить в консоль, не сохраняя в перемену.

2020-04-03 10:19 UTC, dean992008 commented on src/utils.js
> +  let randomPosition;
Это обьвление переменой не нужно. Ее можно будет обьвить как константу внутри `for`, так как эта переменая используеться только в пределах цыкла.

2020-04-03 10:19 UTC, dean992008 commented on src/utils.js
> +  for (i = someArray.length - 1; i > 0; i--) {
Здесь можно сделать `let i` и тогда `i` ну нужно будет обьявлять заранее.

2020-04-03 10:19 UTC, dean992008 commented on src/service/cli/generate.js
> +      type: Object.keys(OfferType)[
В данном случае `Object.keys(OfferType)` лучше закешировать в переменую.

2020-04-03 14:19 UTC, ilyasidorchik commented on src/constants.js
> +  success: 0,
Ссылка не открывается

2020-04-03 14:28 UTC, ilyasidorchik commented on src/utils.js
> +  let randomPosition;
Но в твоём варианте каждый раз будет создавать новая переменная, будет выделяться на неё память.

2020-04-03 14:30 UTC, ilyasidorchik commented on src/utils.js
> +  for (i = someArray.length - 1; i > 0; i--) {
В твоём варианте каждый раз будет тратиться память на новую переменную.

2020-04-04 13:31 UTC, dean992008 commented on src/utils.js
> +  let randomPosition;
Да, но после каждой итерации будет очищаться, а поскольку мы ее обьявим как `const` V8 выделит на нее памяти именно как на int. Так что лучше все-таки перенести в цыкл.

2020-04-04 13:32 UTC, dean992008 commented on src/utils.js
> +  for (i = someArray.length - 1; i > 0; i--) {
С чего она будет тратиться если инициализация 1 раз будет выполняться?

2020-04-04 13:33 UTC, dean992008 commented on src/constants.js
> +  success: 0,
https://up.htmlacademy.ru/nodejs/3/criteries#b7

2020-04-04 13:34 UTC, dean992008 commented on src/data.js
> +const OfferType = {
Не исправлено. Должна быть не переменая а ключи.

2020-04-04 17:18 UTC, ilyasidorchik commented on src/data.js
> +const OfferType = {
Исправил в новом коммите.

2020-04-04 17:30 UTC, ilyasidorchik commented on src/utils.js
> +  let randomPosition;
Разве мой вариант не более оптимизированный?

2020-04-04 17:35 UTC, ilyasidorchik commented on src/utils.js
> +  for (i = someArray.length - 1; i > 0; i--) {
Разве инициализация не будет с каждым ходом цикла?

2020-04-05 11:05 UTC, merged