Add server routing
htmlacademy-nodejs/521287-buy-and-sell-3 pull request #8
Opened 2020-05-17 15:30 UTC by ilyasidorchik

2020-05-17 17:23 UTC, dean992008 requested changes

2020-05-17 17:23 UTC, dean992008 commented on src/express/index.js
> +app.use(`/offers`, offersRoutes);
Нужно сделать модуль с корнем роутера, а здесь использовать его просто как `app.use(router)`.

2020-05-17 17:23 UTC, dean992008 commented on src/express/routes/my-routes.js
> +const ROOT = `/my`;
Я думаю выносить эту строку в константу это лишнее.

2020-05-17 17:23 UTC, dean992008 commented on src/express/routes/offers-routes.js
> +offersRouter.get(`/edit/:id`, (req, res) => res.send(`${ROOT}/edit/:id`));
Нужно сделать чтобы параметр `id` конкатинировался в строку. 
http://joxi.ru/gmvgkOkcqRdgp2

2020-05-17 19:19 UTC, ilyasidorchik commented on src/express/routes/my-routes.js
> +const ROOT = `/my`;
Но ведь зато консистентно.

2020-05-17 19:35 UTC, ilyasidorchik commented on src/express/index.js
> +app.use(`/offers`, offersRoutes);
Разве?

Я делал, как в учебнике:
https://up.htmlacademy.ru/nodejs/3/book/3.12

2020-05-18 10:51 UTC, dean992008 commented on src/express/routes/my-routes.js
> +const ROOT = `/my`;
Ок. Это оставь, всеравно в одном из следующих PR нужно будет удалить.

2020-05-18 10:54 UTC, dean992008 commented on src/express/index.js
> +app.use(`/offers`, offersRoutes);
Я говорю как лучше сделать на примере реаного проекта. 
За роутинг должен отвечать отдельный модуль который импортируется в главный модуль 1 строкой. Представь если корневых роутов было бы 50, мягко говоря `index.js`не совсем красиво выглядел бы. 
Ну и плюс `Single Responsibility` - разделения отвествености роутера и главного модуля.

2020-05-18 21:13 UTC, ilyasidorchik commented on src/express/routes/offers-routes.js
> +offersRouter.get(`/add`, (req, res) => res.send(`${ROOT}/add`));
Так норм обрабатывать айдишники?

2020-05-18 21:13 UTC, ilyasidorchik commented on src/express/routes/offers-routes.js
> +offersRouter.get(`/edit/:id`, (req, res) => res.send(`${ROOT}${req.url}`));
Так норм обрабатывать айдишники?

2020-05-19 08:01 UTC, dean992008 approved these changes

2020-05-19 08:01 UTC, merged