Учебный проект: шаблонизируй это # -----------------------w >8 ------------------------ # Do not modify or remove the line above. # Everything below it will be ignored.
htmlacademy-nodejs/521287-buy-and-sell-3 pull request #9
Opened 2020-05-24 18:18 UTC by ilyasidorchik

Requesting a pull to ilyasidorchik:ase from ilyasidorchik:module3-task2

Write a message for this pull request. The first block
of text is the title and the rest is the description.

2020-05-25 14:08 UTC, dean992008 requested changes

2020-05-25 14:08 UTC, dean992008 commented on markup/sign-up.html
> +
Я думаю в исходники верстки не нужно было вносить изменения. Этот файл лучше откатить .

2020-05-25 14:08 UTC, dean992008 commented on src/express/routes/offers-routes.js
> +const ROOT = `offers`;
Констатнта должна обьвляться перед переменой.

2020-05-25 17:58 UTC, ilyasidorchik commented on src/express/routes/offers-routes.js
> +const ROOT = `offers`;
У меня норм названия файлов путей? Или как можно лучше?

2020-05-26 07:43 UTC, dean992008 commented on src/express/routes/offers-routes.js
> +const ROOT = `offers`;
По путям нормально.

2020-05-26 07:44 UTC, merged